config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :job_offers
  root to: 'home#index'
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_job_offer, only: [:show, :edit, :update, :destroy]
    before_action :check_administrator, only: [:create]

    def index
        @job_offers = JobOffer.all
    end

    def show
    end

    def new
        @job_offer = JobOffer.new
    end

    def create
        @job_offer = JobOffer.new(job_offer_params)

        if @job_offer.save
            redirect_to @job_offer, notice: 'Job offer was successfully created.'
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @job_offer.update(job_offer_params)
            redirect_to @job_offer, notice: 'Job offer was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @job_offer.destroy
        redirect_to job_offers_url, notice: 'Job offer was successfully destroyed.'
    end

    private

    def check_administrator
        unless current_user.administrator?
            redirect_to root_path, alert: 'You do not have permission to perform this action.'
        end
    end
    
    def set_job_offer
        @job_offer = JobOffer.find(params[:id])
    end

    def job_offer_params
        params.require(:job_offer).permit(:title, :description)
    end
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/views/job_offers/_form.html.erb
<%= form_with(model: job_offer, local: true) do |form| %>
    <% if job_offer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job_offer.errors.count, "error") %> prohibited this job offer from being saved:</h2>
  
        <ul>
        <% job_offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/job_offers/edit.html.erb
<h1>Edit Job Offer</h1>
<%= render 'form', job_offer: @job_offer %>
<%= link_to 'Show', @job_offer %> |
<%= link_to 'Back', job_offers_path %>

app/views/job_offers/index.html.erb
<h1>Job Offers</h1>
<ul>
  <% @job_offers.each do |job_offer| %>
    <li>
      <%= link_to job_offer.title, job_offer %>
    </li>
  <% end %>
</ul>
<% if current_user.administrator? %>
  <%= link_to 'New Job Offer', new_job_offer_path %>
<% end %>

app/views/job_offers/new.html.erb
<h1>New Job Offer</h1>
<%= render 'form', job_offer: @job_offer %>
<%= link_to 'Back', job_offers_path %>

app/views/job_offers/show.html.erb
<h1><%= @job_offer.title %></h1>
<p><%= @job_offer.description %></p>
<%= link_to 'Edit', edit_job_offer_path(@job_offer) %> |
<%= link_to 'Back', job_offers_path %>